#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    items=`find ~/workspace/personal -maxdepth 1 -mindepth 1 -type d \
        && find ~/workspace/work -maxdepth 1 -mindepth 1 -type d`
    selected=`echo "$items" | fzf`
fi

dirname=`basename $selected`

tmux switch-client -t $dirname
if [[ $? -eq 0 ]]; then
    exit 0
fi

tmux new-session -c $selected -d -s $dirname \
    && tmux rename-window code \
    && tmux new-window -c $selected\
    && tmux rename-window TDD \
    && tmux next-window \
    && tmux send-keys -t $dirname 'nvim .' C-m \
    && tmux switch-client -t $dirname || tmux new -c $selected -A -s $dirname
