-- https://github.com/neovim/nvim-lspconfig/blob/master/CONFIG.md
require('garbray.lsp-servers.bash')
require('garbray.lsp-servers.css')
require("garbray.lsp-servers.efm")
require('garbray.lsp-servers.emmet')
require('garbray.lsp-servers.go')
require('garbray.lsp-servers.graphql')
require('garbray.lsp-servers.html')
require('garbray.lsp-servers.lua')
require('garbray.lsp-servers.python')
require('garbray.lsp-servers.rust')
require('garbray.lsp-servers.terraform')
require('garbray.lsp-servers.ts')
require('garbray.lsp-servers.vim')
require('garbray.lsp-servers.yaml')
