require("garbray.plugins.cmp")
require("garbray.lsp")

require("garbray.plugins.git-worktree")
require("garbray.plugins.harpoon")
require("garbray.plugins.statusline")
require("garbray.plugins.telescope")
require("garbray.plugins.treesitter")
require("garbray.plugins.tabnine")
require("garbray.plugins.indent-blankline")
require("garbray.plugins.spellsitter")
